name: Pre-Commit

on:
  pull_request:
    branches:
      - main

jobs:
  preCommit:
    name: Pre-Commit Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
